### ISSUE TITLE
Prioritization

### ISSUE THREAD

**Issue by curran** [datavis-tech/kibana-chord#18]
Priorities:
- [x] Add labels for chord groups #3
- [x] Add Filter to Schema #11
- [x] Add radial arcs to indicate chord groups #2 
- [x] Table Skeleton #22
- [x] Event listener for chord clicking #23
- [x] Make custom ES query based on clicked chord #26
- [x] Populate table with custom ES query results #27
- [x] Format timestamp in table #36
- [x] Dynamic time parameters in ES query #33
- [x] Update table on interval #42
- [x] Sort table to most recent #39
- [x] Add Source PG and Dest PG to table #40
- [x] Highlight clicked chord #41
- [x] Add hover interaction to radial arcs #4
- [x] Shorten date format in table #52
- [x] Fix Error on Empty Response #25
- [x] Un-select chord #50 
- [x] add a table header #55 
- [x] Fixed coloring #56
- [x] Bold text on ribbon select #57
- [x] Add tooltips to chords #5 
- [x] Use ES scroll for pagination #34 
- [ ] Hide everything when empty data #49
- [x] Make sure table and chord are accurate #31 
- [ ] Make icon look like Chord Diagram #1 
- [ ] Update README with new screenshot #53

Possibly outdated ideas not worth pursuing:
- [ ] Respond to Resize #6
